/* autogenerated by GraphKB (c) Dmitry Ponyatov <dponyatov@gmail.com> */
#ifndef _H_HPP
#define _H_HPP

#include <iostream>
using namespace std;


struct Sym {
	Sym(string);
};

extern int yylex();
extern int yylineno;
extern char* yytext;
#define TOC(C,X) { yylval.o = new C(yytext); return X; }
extern int yyparse();
extern void yyerror(string);

#endif // _H_HPP
